package mil.decea.mentorpgapi.domain.user;
import mil.decea.mentorpgapi.util.ConvertDateToMillis;
import java.util.List;

public record UserRecord(
	Long id,
	String cpf,
	Titulacao titulacao,
	Posto posto,
	String quadro,
	String especialidade,
	String nomeGuerra,
	String nomeCompleto,
	Sexo sexo,
	ForcaSingular forcaSingular,
	String ultimaPromocao,
	boolean pttc,
	int antiguidadeRelativa,
	String senha,
	String role,
	String celular,
	String email,
	String identidade,
	String dataNascimento,
	String dataPraca,
	String proximaPromocao,
	String saram,
	String observacoes,
	List<?> documents) {
	public UserRecord(User obj) {
		this(obj.getId(),
			obj.getCpf(),
			obj.getTitulacao(),
			obj.getPosto(),
			obj.getQuadro(),
			obj.getEspecialidade(),
			obj.getNomeGuerra(),
			obj.getNomeCompleto(),
			obj.getSexo(),
			obj.getForcaSingular(),
			ConvertDateToMillis.converter(obj.getUltimaPromocao())+"",
			obj.isPttc(),
			obj.getAntiguidadeRelativa(),
			obj.getSenha(),
			obj.getRole(),
			obj.getCelular(),
			obj.getEmail(),
			obj.getIdentidade(),
			ConvertDateToMillis.converter(obj.getDataNascimento())+"",
			ConvertDateToMillis.converter(obj.getDataPraca())+"",
			ConvertDateToMillis.converter(obj.getProximaPromocao())+"",
			obj.getSaram(),
			obj.getObservacoes(),
			obj.getDocuments());
	}
}