package mil.decea.mentorpgapi.domain.user;
import mil.decea.mentorpgapi.util.ConvertDateToMillis;
import java.util.List;
import java.lang.Long;

public record UserRecord(
	int antiguidadeRelativa,
	Titulacao titulacao,
	Posto posto,
	String quadro,
	String especialidade,
	String nomeGuerra,
	String cpf,
	String nomeCompleto,
	boolean pttc,
	String senha,
	ForcaSingular forcaSingular,
	String role,
	String dataPraca,
	String email,
	String celular,
	String proximaPromocao,
	UserImageRecord userImageRecord,
	String dataNascimento,
	String observacoes,
	String saram,
	List<?> documents,
	String identidade,
	String ultimaPromocao,
	Sexo sexo,
	Long id,
	boolean ativo) {
	public UserRecord(User obj) {
		this(obj.getAntiguidadeRelativa(),
			obj.getTitulacao(),
			obj.getPosto(),
			obj.getQuadro(),
			obj.getEspecialidade(),
			obj.getNomeGuerra(),
			obj.getCpf(),
			obj.getNomeCompleto(),
			obj.isPttc(),
			obj.getSenha(),
			obj.getForcaSingular(),
			obj.getRole(),
			ConvertDateToMillis.converter(obj.getDataPraca())+"",
			obj.getEmail(),
			obj.getCelular(),
			ConvertDateToMillis.converter(obj.getProximaPromocao())+"",
			new UserImageRecord(obj.getUserImage()),
			ConvertDateToMillis.converter(obj.getDataNascimento())+"",
			obj.getObservacoes(),
			obj.getSaram(),
			obj.getDocuments(),
			obj.getIdentidade(),
			ConvertDateToMillis.converter(obj.getUltimaPromocao())+"",
			obj.getSexo(),
			obj.getId(),
			obj.isAtivo());
	}
}