package mil.decea.mentorpgapi.domain.user;
import mil.decea.mentorpgapi.util.ConvertDateToMillis;
import java.util.List;

public record UserRecord(
	Long id,
	String cpf,
	Titulacao titulacao,
	Posto posto,
	String quadro,
	String especialidade,
	String nomeGuerra,
	String nomeCompleto,
	Sexo sexo,
	ForcaSingular forcaSingular,
	String ultimaPromocao,
	boolean pttc,
	int antiguidadeRelativa,
	String senha,
	String role,
	String rua,
	String numero,
	String complemento,
	String bairro,
	String cidade,
	String uf,
	String cep,
	String emailPessoal,
	String emailInstitucional,
	int emailPreferencial,
	String telCelular,
	String telResidencial,
	String telTrabalho,
	String ramal,
	String identidade,
	String passaporte,
	String nacionalidade,
	String naturalidade,
	String dataNascimento,
	String validadePassaporte,
	String dataPraca,
	String proximaPromocao,
	String banco,
	String agencia,
	String conta,
	String saram,
	String observacoes,
	List<?> documents) {
	public UserRecord(User obj) {
		this(obj.getId(),
			obj.getCpf(),
			obj.getTitulacao(),
			obj.getPosto(),
			obj.getQuadro(),
			obj.getEspecialidade(),
			obj.getNomeGuerra(),
			obj.getNomeCompleto(),
			obj.getSexo(),
			obj.getForcaSingular(),
			ConvertDateToMillis.converter(obj.getUltimaPromocao())+"",
			obj.isPttc(),
			obj.getAntiguidadeRelativa(),
			obj.getSenha(),
			obj.getRole(),
			obj.getEndereco().getRua(),
			obj.getEndereco().getNumero(),
			obj.getEndereco().getComplemento(),
			obj.getEndereco().getBairro(),
			obj.getEndereco().getCidade(),
			obj.getEndereco().getUf(),
			obj.getEndereco().getCep(),
			obj.getContato().getEmailPessoal(),
			obj.getContato().getEmailInstitucional(),
			obj.getContato().getEmailPreferencial(),
			obj.getContato().getTelCelular(),
			obj.getContato().getTelResidencial(),
			obj.getContato().getTelTrabalho(),
			obj.getContato().getRamal(),
			obj.getIdentidade(),
			obj.getPassaporte(),
			obj.getNacionalidade(),
			obj.getNaturalidade(),
			ConvertDateToMillis.converter(obj.getDataNascimento())+"",
			ConvertDateToMillis.converter(obj.getValidadePassaporte())+"",
			ConvertDateToMillis.converter(obj.getDataPraca())+"",
			ConvertDateToMillis.converter(obj.getProximaPromocao())+"",
			obj.getBanco(),
			obj.getAgencia(),
			obj.getConta(),
			obj.getSaram(),
			obj.getObservacoes(),
			obj.getDocuments());
	}
}